#!/bin/bash

# Compilación de los archivos .cpp
g++ -o hilo1 hilo1.cpp -lpthread
g++ -o hilo2 hilo2.cpp -lpthread
g++ -o hilo3 hilo3.cpp -lpthread

# Verificar si la compilación fue exitosa antes de ejecutar los programas
if [ $? -eq 0 ]; then
    echo "Compilación exitosa. Ejecutando los hilos..."

    # Ejecutar los programas en segundo plano
    ./hilo1 &
    PID1=$!

    ./hilo2 &
    PID2=$!

    ./hilo3 &
    PID3=$!

    # Esperar a que todos los procesos finalicen
    wait $PID1
    wait $PID2
    wait $PID3

    echo "Todos los hilos han terminado."
else
    echo "Error en la compilación. Por favor, corrige los errores antes de ejecutar los programas."
fi
